server:
  port: 9081

spring:
  config:
    import: 
      - nacos: ${spring.cloud.nacos.discovery.service}
  cloud:
    nacos:
      discovery:
        server-addr: 26.99.234.0:8848
        metadata:
          my-key: my-meta-value
        service: teacher
        username: nacos
        password: nacos
        port: 9081
        weight: 1
        ephemeral: true
      config:
        server-addr: 26.99.234.0:8848
        file-extension: yml
        username: nacos
        password: nacos